"""Constants used throughout the AccOps Agent."""

# LLM Configuration Defaults
DEFAULT_LLM_MODEL = "gpt-4"
DEFAULT_LLM_TEMPERATURE = 0.7
DEFAULT_LLM_MAX_TOKENS = 2000

# Temperature settings for specific tasks
TEMPERATURE_DIAGNOSTIC_ANALYSIS = 0.3
TEMPERATURE_REASONING_PLANNING = 0.5
TEMPERATURE_ACTION_GENERATION = 0.3
TEMPERATURE_VERIFICATION = 0.3

# Graph/Workflow Defaults
DEFAULT_MAX_ITERATIONS = 10
DEFAULT_EXECUTION_HISTORY_MAX_SIZE = 100

# Safety Constraint Defaults
DEFAULT_MAX_CHANGES_PER_MINUTE = 10
DEFAULT_RATE_LIMIT_WINDOW_SECONDS = 60

# Pydantic Validation Limits
ACTION_PRIORITY_MIN = 1
ACTION_PRIORITY_MAX = 5
EFFECTIVENESS_MIN = 1
EFFECTIVENESS_MAX = 10

# Text Parsing Limits
VERIFICATION_SUMMARY_MAX_LENGTH = 200
